#!/usr/bin/env bash
# Bash script to install and configure HAProxy as a load balancer

set -e

# Install HAProxy
apt-get update
apt-get -y install haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup existing config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 18.206.58.171:80 check
    server web02 52.54.213.138:80 check
    http-response set-header X-Served-By %[srv_name]
EOL

# Restart HAProxy
systemctl enable haproxy
systemctl restart haproxy
